# Air Mesurements from April to October 2019

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../bcn_open_data/air_quality_2019.csv',index_col=[0])

In [3]:
df.head()

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,V20,H21,V21,H22,V22,H23,V23,H24,V24,CODI_PROVINCIA;PROVINCIA;CODI_MUNICIPI;MUNICIPI;ESTACIO;CODI_CONTAMINANT;ANY;MES;DIA;H01;V01;H02;V02;H03;V03;H04;V04;H05;V05;H06;V06;H07;V07;H08;V08;H09;V09;H10;V10;H11;V11;H12;V12;H13;V13;H14;V14;H15;V15;H16;V16;H17;V17;H18;V18;H19;V19;H20;V20;H21;V21;H22;V22;H23;V23;H24;V24
0,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,2.0,1.0,...,V,3.0,V,1.0,V,1.0,V,1.0,V,NaN
1,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,3.0,1.0,...,V,2.0,V,2.0,V,2.0,V,2.0,V,NaN
2,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,4.0,1.0,...,V,2.0,V,1.0,V,2.0,V,2.0,V,NaN
3,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,5.0,2.0,...,V,2.0,V,2.0,V,1.0,V,2.0,V,NaN
4,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,6.0,1.0,...,V,2.0,V,2.0,V,1.0,V,3.0,V,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7989 entries, 0 to 1208
Data columns (total 58 columns):
 #   Column                                                                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                --------------  -----
 0   CODI_PROVINCIA                                                                                                                                                                                                                                                                        5772 non-null   float64
 1   PROVINCIA                                                                                                                                                                                                                                                                             5772 non-null   object
 2   CODI_MUNICIPI                                                                                                                                                                                                                                                                         5772 non-null   float64
 3   MUNICIPI                                                                                                                                                                                                                                                                              5772 non-null   object
 4   ESTACIO                                                                                                                                                                                                                                                                               5772 non-null   float64
 5   CODI_CONTAMINANT                                                                                                                                                                                                                                                                      5772 non-null   float64
 6   ANY                                                                                                                                                                                                                                                                                   5772 non-null   float64
 7   MES                                                                                                                                                                                                                                                                                   5772 non-null   float64
 8   DIA                                                                                                                                                                                                                                                                                   5772 non-null   float64
 9   H01                                                                                                                                                                                                                                                                                   5732 non-null   float64
 10  V01                                                                                                                                                                                                                                                                                   5772 non-null   object
 11  H02                                                                                                                                                                                                                                                                                   5732 non-null   float64
 12  V02                                                                                                                                                                                                                                                                                   5772 non-null   object
 13  H03                                                                                                                                                                                                                                                                                   5687 non-null   float64
 14  V03                                                                                                                                                                                                                                                                                   5772 non-null   object
 15  H04                                                                                                                                                                                                                                                                                   5726 non-null   float64
 16  V04                                                                                                                                                                                                                                                                                   5772 non-null   object
 17  H05                                                                                                                                                                                                                                                                                   5727 non-null   float64
 18  V05                                                                                                                                                                                                                                                                                   5772 non-null   object
 19  H06                                                                                                                                                                                                                                                                                   5725 non-null   float64
 20  V06                                                                                                                                                                                                                                                                                   5772 non-null   object
 21  H07                                                                                                                                                                                                                                                                                   5715 non-null   float64
 22  V07                                                                                                                                                                                                                                                                                   5772 non-null   object
 23  H08                                                                                                                                                                                                                                                                                   5672 non-null   float64
 24  V08                                                                                                                                                                                                                                                                                   5772 non-null   object
 25  H09                                                                                                                                                                                                                                                                                   5665 non-null   float64
 26  V09                                                                                                                                                                                                                                                                                   5772 non-null   object
 27  H10                                                                                                                                                                                                                                                                                   5667 non-null   float64
 28  V10                                                                                                                                                                                                                                                                                   5772 non-null   object
 29  H11                                                                                                                                                                                                                                                                                   5526 non-null   float64
 30  V11                                                                                                                                                                                                                                                                                   5772 non-null   object
 31  H12                                                                                                                                                                                                                                                                                   5504 non-null   float64
 32  V12                                                                                                                                                                                                                                                                                   5772 non-null   object
 33  H13                                                                                                                                                                                                                                                                                   5510 non-null   float64
 34  V13                                                                                                                                                                                                                                                                                   5772 non-null   object
 35  H14                                                                                                                                                                                                                                                                                   5518 non-null   float64
 36  V14                                                                                                                                                                                                                                                                                   5772 non-null   object
 37  H15                                                                                                                                                                                                                                                                                   5569 non-null   float64
 38  V15                                                                                                                                                                                                                                                                                   5772 non-null   object
 39  H16                                                                                                                                                                                                                                                                                   5610 non-null   float64
 40  V16                                                                                                                                                                                                                                                                                   5772 non-null   object
 41  H17                                                                                                                                                                                                                                                                                   5686 non-null   float64
 42  V17                                                                                                                                                                                                                                                                                   5772 non-null   object
 43  H18                                                                                                                                                                                                                                                                                   5651 non-null   float64
 44  V18                                                                                                                                                                                                                                                                                   5772 non-null   object
 45  H19                                                                                                                                                                                                                                                                                   5653 non-null   float64
 46  V19                                                                                                                                                                                                                                                                                   5772 non-null   object
 47  H20                                                                                                                                                                                                                                                                                   5660 non-null   float64
 48  V20                                                                                                                                                                                                                                                                                   5772 non-null   object
 49  H21                                                                                                                                                                                                                                                                                   5621 non-null   float64
 50  V21                                                                                                                                                                                                                                                                                   5772 non-null   object
 51  H22                                                                                                                                                                                                                                                                                   5580 non-null   float64
 52  V22                                                                                                                                                                                                                                                                                   5772 non-null   object
 53  H23                                                                                                                                                                                                                                                                                   5270 non-null   float64
 54  V23                                                                                                                                                                                                                                                                                   5772 non-null   object
 55  H24                                                                                                                                                                                                                                                                                   3995 non-null   float64
 56  V24                                                                                                                                                                                                                                                                                   5772 non-null   object
 57  CODI_PROVINCIA;PROVINCIA;CODI_MUNICIPI;MUNICIPI;ESTACIO;CODI_CONTAMINANT;ANY;MES;DIA;H01;V01;H02;V02;H03;V03;H04;V04;H05;V05;H06;V06;H07;V07;H08;V08;H09;V09;H10;V10;H11;V11;H12;V12;H13;V13;H14;V14;H15;V15;H16;V16;H17;V17;H18;V18;H19;V19;H20;V20;H21;V21;H22;V22;H23;V23;H24;V24  2217 non-null   object
dtypes: float64(31), object(27)
memory usage: 3.6+ MB

In [5]:
numeric= df.select_dtypes(include=np.number)

In [6]:
numeric

,CODI_PROVINCIA,CODI_MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,H02,H03,...,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24
0,8.0,19.0,4.0,7.0,2019.0,4.0,2.0,1.0,1.0,3.0,...,NaN,NaN,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0
1,8.0,19.0,4.0,7.0,2019.0,4.0,3.0,1.0,1.0,1.0,...,6.0,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0
2,8.0,19.0,4.0,7.0,2019.0,4.0,4.0,1.0,1.0,2.0,...,8.0,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0
3,8.0,19.0,4.0,7.0,2019.0,4.0,5.0,2.0,1.0,8.0,...,4.0,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0
4,8.0,19.0,4.0,7.0,2019.0,4.0,6.0,1.0,1.0,1.0,...,3.0,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,8.0,19.0,57.0,14.0,2019.0,10.0,27.0,12.0,4.0,NaN,...,82.0,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0
1205,8.0,19.0,57.0,14.0,2019.0,10.0,28.0,15.0,34.0,42.0,...,48.0,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0
1206,8.0,19.0,57.0,14.0,2019.0,10.0,29.0,41.0,50.0,63.0,...,26.0,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0
1207,8.0,19.0,57.0,14.0,2019.0,10.0,30.0,1.0,1.0,1.0,...,74.0,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0
1208,8.0,19.0,57.0,14.0,2019.0,10.0,31.0,43.0,62.0,66.0,...,42.0,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0

In [7]:
categoric = df.select_dtypes(exclude = np.number)

In [8]:
categoric

,PROVINCIA,MUNICIPI,V01,V02,V03,V04,V05,V06,V07,V08,...,V16,V17,V18,V19,V20,V21,V22,V23,V24,CODI_PROVINCIA;PROVINCIA;CODI_MUNICIPI;MUNICIPI;ESTACIO;CODI_CONTAMINANT;ANY;MES;DIA;H01;V01;H02;V02;H03;V03;H04;V04;H05;V05;H06;V06;H07;V07;H08;V08;H09;V09;H10;V10;H11;V11;H12;V12;H13;V13;H14;V14;H15;V15;H16;V16;H17;V17;H18;V18;H19;V19;H20;V20;H21;V21;H22;V22;H23;V23;H24;V24
0,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,N,V,V,V,V,V,V,V,V,NaN
1,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
2,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
3,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
4,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,Barcelona,Barcelona,V,V,N,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
1205,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
1206,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
1207,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
1208,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN

#### Dropping column 58 which is a long string with all the values of this DF.

In [9]:
df.drop('CODI_PROVINCIA;PROVINCIA;CODI_MUNICIPI;MUNICIPI;ESTACIO;CODI_CONTAMINANT;ANY;MES;DIA;H01;V01;H02;V02;H03;V03;H04;V04;H05;V05;H06;V06;H07;V07;H08;V08;H09;V09;H10;V10;H11;V11;H12;V12;H13;V13;H14;V14;H15;V15;H16;V16;H17;V17;H18;V18;H19;V19;H20;V20;H21;V21;H22;V22;H23;V23;H24;V24', axis='columns', inplace=True)

In [13]:
df = df.select_dtypes(exclude = object).copy()

In [14]:
df

,CODI_PROVINCIA,CODI_MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,H02,H03,...,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24
0,8.0,19.0,4.0,7.0,2019.0,4.0,2.0,1.0,1.0,3.0,...,NaN,NaN,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0
1,8.0,19.0,4.0,7.0,2019.0,4.0,3.0,1.0,1.0,1.0,...,6.0,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0
2,8.0,19.0,4.0,7.0,2019.0,4.0,4.0,1.0,1.0,2.0,...,8.0,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0
3,8.0,19.0,4.0,7.0,2019.0,4.0,5.0,2.0,1.0,8.0,...,4.0,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0
4,8.0,19.0,4.0,7.0,2019.0,4.0,6.0,1.0,1.0,1.0,...,3.0,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,8.0,19.0,57.0,14.0,2019.0,10.0,27.0,12.0,4.0,NaN,...,82.0,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0
1205,8.0,19.0,57.0,14.0,2019.0,10.0,28.0,15.0,34.0,42.0,...,48.0,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0
1206,8.0,19.0,57.0,14.0,2019.0,10.0,29.0,41.0,50.0,63.0,...,26.0,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0
1207,8.0,19.0,57.0,14.0,2019.0,10.0,30.0,1.0,1.0,1.0,...,74.0,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0
1208,8.0,19.0,57.0,14.0,2019.0,10.0,31.0,43.0,62.0,66.0,...,42.0,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0

In [14]:
df.isnull().sum()

CODI_PROVINCIA      2217
PROVINCIA           2217
CODI_MUNICIPI       2217
MUNICIPI            2217
ESTACIO             2217
CODI_CONTAMINANT    2217
ANY                 2217
MES                 2217
DIA                 2217
H01                 2257
V01                 2217
H02                 2257
V02                 2217
H03                 2302
V03                 2217
H04                 2263
V04                 2217
H05                 2262
V05                 2217
H06                 2264
V06                 2217
H07                 2274
V07                 2217
H08                 2317
V08                 2217
H09                 2324
V09                 2217
H10                 2322
V10                 2217
H11                 2463
V11                 2217
H12                 2485
V12                 2217
H13                 2479
V13                 2217
H14                 2471
V14                 2217
H15                 2420
V15                 2217
H16                 2379
V16                 2217
H17                 2303
V17                 2217
H18                 2338
V18                 2217
H19                 2336
V19                 2217
H20                 2329
V20                 2217
H21                 2368
V21                 2217
H22                 2409
V22                 2217
H23                 2719
V23                 2217
H24                 3994
V24                 2217
dtype: int64

In [35]:
df.shape

(7989, 58)

In [37]:
df

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,2.0,1.0,...,8.0,V,3.0,V,1.0,V,1.0,V,1.0,V
1,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,3.0,1.0,...,3.0,V,2.0,V,2.0,V,2.0,V,2.0,V
2,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,4.0,1.0,...,2.0,V,2.0,V,1.0,V,2.0,V,2.0,V
3,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,5.0,2.0,...,3.0,V,2.0,V,2.0,V,1.0,V,2.0,V
4,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,6.0,1.0,...,6.0,V,2.0,V,2.0,V,1.0,V,3.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,8.0,Barcelona,19.0,Barcelona,57.0,14.0,2019.0,10.0,27.0,12.0,...,36.0,V,33.0,V,25.0,V,11.0,V,18.0,V
1205,8.0,Barcelona,19.0,Barcelona,57.0,14.0,2019.0,10.0,28.0,15.0,...,3.0,V,21.0,V,41.0,V,31.0,V,36.0,V
1206,8.0,Barcelona,19.0,Barcelona,57.0,14.0,2019.0,10.0,29.0,41.0,...,5.0,V,1.0,V,1.0,V,2.0,V,1.0,V
1207,8.0,Barcelona,19.0,Barcelona,57.0,14.0,2019.0,10.0,30.0,1.0,...,8.0,V,63.0,V,71.0,V,66.0,V,52.0,V
1208,8.0,Barcelona,19.0,Barcelona,57.0,14.0,2019.0,10.0,31.0,43.0,...,16.0,V,17.0,V,16.0,V,54.0,V,55.0,V

In [38]:
df.drop(columns=['CODI_PROVINCIA', 'PROVINCIA', 'CODI_MUNICIPI', 'MUNICIPI'], inplace=True)

In [39]:
df

,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,V01,H02,V02,H03,...,H20,V20,H21,V21,H22,V22,H23,V23,H24,V24
0,4.0,7.0,2019.0,4.0,2.0,1.0,V,1.0,V,3.0,...,8.0,V,3.0,V,1.0,V,1.0,V,1.0,V
1,4.0,7.0,2019.0,4.0,3.0,1.0,V,1.0,V,1.0,...,3.0,V,2.0,V,2.0,V,2.0,V,2.0,V
2,4.0,7.0,2019.0,4.0,4.0,1.0,V,1.0,V,2.0,...,2.0,V,2.0,V,1.0,V,2.0,V,2.0,V
3,4.0,7.0,2019.0,4.0,5.0,2.0,V,1.0,V,8.0,...,3.0,V,2.0,V,2.0,V,1.0,V,2.0,V
4,4.0,7.0,2019.0,4.0,6.0,1.0,V,1.0,V,1.0,...,6.0,V,2.0,V,2.0,V,1.0,V,3.0,V
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,57.0,14.0,2019.0,10.0,27.0,12.0,V,4.0,V,NaN,...,36.0,V,33.0,V,25.0,V,11.0,V,18.0,V
1205,57.0,14.0,2019.0,10.0,28.0,15.0,V,34.0,V,42.0,...,3.0,V,21.0,V,41.0,V,31.0,V,36.0,V
1206,57.0,14.0,2019.0,10.0,29.0,41.0,V,50.0,V,63.0,...,5.0,V,1.0,V,1.0,V,2.0,V,1.0,V
1207,57.0,14.0,2019.0,10.0,30.0,1.0,V,1.0,V,1.0,...,8.0,V,63.0,V,71.0,V,66.0,V,52.0,V
1208,57.0,14.0,2019.0,10.0,31.0,43.0,V,62.0,V,66.0,...,16.0,V,17.0,V,16.0,V,54.0,V,55.0,V

In [18]:
df['ANY'] = df['ANY'].apply(lambda x: str(x))

In [22]:
df['MES'] = df['MES'].apply(lambda x: str(x))

In [24]:
(df["ANY"].astype(str).apply(lambda x: x[:-2]) + "-"+df["MES"].astype(str).apply(lambda x: x[:-2]) + "-" + df["DIA"].astype(str).apply(lambda x: x[:-2]))

0         2019-4-2
1         2019-4-3
2         2019-4-4
3         2019-4-5
4         2019-4-6
           ...
1204    2019-10-27
1205    2019-10-28
1206    2019-10-29
1207    2019-10-30
1208    2019-10-31
Length: 7989, dtype: object

In [23]:
df['DIA'] = df['DIA'].apply(lambda x: str(x))

In [25]:
df.isnull().sum()

Unnamed: 0             0
ESTACIO             2217
CODI_CONTAMINANT    2217
ANY                    0
MES                    0
DIA                    0
H01                 2257
V01                 2217
H02                 2257
V02                 2217
H03                 2302
V03                 2217
H04                 2263
V04                 2217
H05                 2262
V05                 2217
H06                 2264
V06                 2217
H07                 2274
V07                 2217
H08                 2317
V08                 2217
H09                 2324
V09                 2217
H10                 2322
V10                 2217
H11                 2463
V11                 2217
H12                 2485
V12                 2217
H13                 2479
V13                 2217
H14                 2471
V14                 2217
H15                 2420
V15                 2217
H16                 2379
V16                 2217
H17                 2303
V17                 2217
H18                 2338
V18                 2217
H19                 2336
V19                 2217
H20                 2329
V20                 2217
H21                 2368
V21                 2217
H22                 2409
V22                 2217
H23                 2719
V23                 2217
H24                 3994
V24                 2217
dtype: int64