# Air Measurements from April to October 2019

In [17]:
import pandas as pd
import numpy as np

In [18]:
df = pd.read_csv('../bcn_open_data/air_quality_2019.csv',index_col=[0])

In [19]:
df.head()

,CODI_PROVINCIA,PROVINCIA,CODI_MUNICIPI,MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,...,V20,H21,V21,H22,V22,H23,V23,H24,V24,CODI_PROVINCIA;PROVINCIA;CODI_MUNICIPI;MUNICIPI;ESTACIO;CODI_CONTAMINANT;ANY;MES;DIA;H01;V01;H02;V02;H03;V03;H04;V04;H05;V05;H06;V06;H07;V07;H08;V08;H09;V09;H10;V10;H11;V11;H12;V12;H13;V13;H14;V14;H15;V15;H16;V16;H17;V17;H18;V18;H19;V19;H20;V20;H21;V21;H22;V22;H23;V23;H24;V24
0,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,2.0,1.0,...,V,3.0,V,1.0,V,1.0,V,1.0,V,NaN
1,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,3.0,1.0,...,V,2.0,V,2.0,V,2.0,V,2.0,V,NaN
2,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,4.0,1.0,...,V,2.0,V,1.0,V,2.0,V,2.0,V,NaN
3,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,5.0,2.0,...,V,2.0,V,2.0,V,1.0,V,2.0,V,NaN
4,8.0,Barcelona,19.0,Barcelona,4.0,7.0,2019.0,4.0,6.0,1.0,...,V,2.0,V,2.0,V,1.0,V,3.0,V,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7989 entries, 0 to 1208
Data columns (total 58 columns):
 #   Column                                                                                                                                                                                                                                                                                Non-Null Count  Dtype
---  ------                                                                                                                                                                                                                                                                                --------------  -----
 0   CODI_PROVINCIA                                                                                                                                                                                                                                                                        5772 non-null   float64
 1   PROVINCIA                                                                                                                                                                                                                                                                             5772 non-null   object
 2   CODI_MUNICIPI                                                                                                                                                                                                                                                                         5772 non-null   float64
 3   MUNICIPI                                                                                                                                                                                                                                                                              5772 non-null   object
 4   ESTACIO                                                                                                                                                                                                                                                                               5772 non-null   float64
 5   CODI_CONTAMINANT                                                                                                                                                                                                                                                                      5772 non-null   float64
 6   ANY                                                                                                                                                                                                                                                                                   5772 non-null   float64
 7   MES                                                                                                                                                                                                                                                                                   5772 non-null   float64
 8   DIA                                                                                                                                                                                                                                                                                   5772 non-null   float64
 9   H01                                                                                                                                                                                                                                                                                   5732 non-null   float64
 10  V01                                                                                                                                                                                                                                                                                   5772 non-null   object
 11  H02                                                                                                                                                                                                                                                                                   5732 non-null   float64
 12  V02                                                                                                                                                                                                                                                                                   5772 non-null   object
 13  H03                                                                                                                                                                                                                                                                                   5687 non-null   float64
 14  V03                                                                                                                                                                                                                                                                                   5772 non-null   object
 15  H04                                                                                                                                                                                                                                                                                   5726 non-null   float64
 16  V04                                                                                                                                                                                                                                                                                   5772 non-null   object
 17  H05                                                                                                                                                                                                                                                                                   5727 non-null   float64
 18  V05                                                                                                                                                                                                                                                                                   5772 non-null   object
 19  H06                                                                                                                                                                                                                                                                                   5725 non-null   float64
 20  V06                                                                                                                                                                                                                                                                                   5772 non-null   object
 21  H07                                                                                                                                                                                                                                                                                   5715 non-null   float64
 22  V07                                                                                                                                                                                                                                                                                   5772 non-null   object
 23  H08                                                                                                                                                                                                                                                                                   5672 non-null   float64
 24  V08                                                                                                                                                                                                                                                                                   5772 non-null   object
 25  H09                                                                                                                                                                                                                                                                                   5665 non-null   float64
 26  V09                                                                                                                                                                                                                                                                                   5772 non-null   object
 27  H10                                                                                                                                                                                                                                                                                   5667 non-null   float64
 28  V10                                                                                                                                                                                                                                                                                   5772 non-null   object
 29  H11                                                                                                                                                                                                                                                                                   5526 non-null   float64
 30  V11                                                                                                                                                                                                                                                                                   5772 non-null   object
 31  H12                                                                                                                                                                                                                                                                                   5504 non-null   float64
 32  V12                                                                                                                                                                                                                                                                                   5772 non-null   object
 33  H13                                                                                                                                                                                                                                                                                   5510 non-null   float64
 34  V13                                                                                                                                                                                                                                                                                   5772 non-null   object
 35  H14                                                                                                                                                                                                                                                                                   5518 non-null   float64
 36  V14                                                                                                                                                                                                                                                                                   5772 non-null   object
 37  H15                                                                                                                                                                                                                                                                                   5569 non-null   float64
 38  V15                                                                                                                                                                                                                                                                                   5772 non-null   object
 39  H16                                                                                                                                                                                                                                                                                   5610 non-null   float64
 40  V16                                                                                                                                                                                                                                                                                   5772 non-null   object
 41  H17                                                                                                                                                                                                                                                                                   5686 non-null   float64
 42  V17                                                                                                                                                                                                                                                                                   5772 non-null   object
 43  H18                                                                                                                                                                                                                                                                                   5651 non-null   float64
 44  V18                                                                                                                                                                                                                                                                                   5772 non-null   object
 45  H19                                                                                                                                                                                                                                                                                   5653 non-null   float64
 46  V19                                                                                                                                                                                                                                                                                   5772 non-null   object
 47  H20                                                                                                                                                                                                                                                                                   5660 non-null   float64
 48  V20                                                                                                                                                                                                                                                                                   5772 non-null   object
 49  H21                                                                                                                                                                                                                                                                                   5621 non-null   float64
 50  V21                                                                                                                                                                                                                                                                                   5772 non-null   object
 51  H22                                                                                                                                                                                                                                                                                   5580 non-null   float64
 52  V22                                                                                                                                                                                                                                                                                   5772 non-null   object
 53  H23                                                                                                                                                                                                                                                                                   5270 non-null   float64
 54  V23                                                                                                                                                                                                                                                                                   5772 non-null   object
 55  H24                                                                                                                                                                                                                                                                                   3995 non-null   float64
 56  V24                                                                                                                                                                                                                                                                                   5772 non-null   object
 57  CODI_PROVINCIA;PROVINCIA;CODI_MUNICIPI;MUNICIPI;ESTACIO;CODI_CONTAMINANT;ANY;MES;DIA;H01;V01;H02;V02;H03;V03;H04;V04;H05;V05;H06;V06;H07;V07;H08;V08;H09;V09;H10;V10;H11;V11;H12;V12;H13;V13;H14;V14;H15;V15;H16;V16;H17;V17;H18;V18;H19;V19;H20;V20;H21;V21;H22;V22;H23;V23;H24;V24  2217 non-null   object
dtypes: float64(31), object(27)
memory usage: 3.6+ MB

In [5]:
numeric= df.select_dtypes(include=np.number)

In [6]:
numeric

,CODI_PROVINCIA,CODI_MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,H02,H03,...,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24
0,8.0,19.0,4.0,7.0,2019.0,4.0,2.0,1.0,1.0,3.0,...,NaN,NaN,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0
1,8.0,19.0,4.0,7.0,2019.0,4.0,3.0,1.0,1.0,1.0,...,6.0,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0
2,8.0,19.0,4.0,7.0,2019.0,4.0,4.0,1.0,1.0,2.0,...,8.0,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0
3,8.0,19.0,4.0,7.0,2019.0,4.0,5.0,2.0,1.0,8.0,...,4.0,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0
4,8.0,19.0,4.0,7.0,2019.0,4.0,6.0,1.0,1.0,1.0,...,3.0,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,8.0,19.0,57.0,14.0,2019.0,10.0,27.0,12.0,4.0,NaN,...,82.0,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0
1205,8.0,19.0,57.0,14.0,2019.0,10.0,28.0,15.0,34.0,42.0,...,48.0,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0
1206,8.0,19.0,57.0,14.0,2019.0,10.0,29.0,41.0,50.0,63.0,...,26.0,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0
1207,8.0,19.0,57.0,14.0,2019.0,10.0,30.0,1.0,1.0,1.0,...,74.0,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0
1208,8.0,19.0,57.0,14.0,2019.0,10.0,31.0,43.0,62.0,66.0,...,42.0,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0

In [17]:
categoric = df.select_dtypes(exclude = np.number)

In [8]:
categoric

,PROVINCIA,MUNICIPI,V01,V02,V03,V04,V05,V06,V07,V08,...,V16,V17,V18,V19,V20,V21,V22,V23,V24,CODI_PROVINCIA;PROVINCIA;CODI_MUNICIPI;MUNICIPI;ESTACIO;CODI_CONTAMINANT;ANY;MES;DIA;H01;V01;H02;V02;H03;V03;H04;V04;H05;V05;H06;V06;H07;V07;H08;V08;H09;V09;H10;V10;H11;V11;H12;V12;H13;V13;H14;V14;H15;V15;H16;V16;H17;V17;H18;V18;H19;V19;H20;V20;H21;V21;H22;V22;H23;V23;H24;V24
0,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,N,V,V,V,V,V,V,V,V,NaN
1,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
2,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
3,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
4,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,Barcelona,Barcelona,V,V,N,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
1205,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
1206,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
1207,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN
1208,Barcelona,Barcelona,V,V,V,V,V,V,V,V,...,V,V,V,V,V,V,V,V,V,NaN

#### Dropping column 58 which is a long string with all the values of this DF.

In [20]:
df.drop('CODI_PROVINCIA;PROVINCIA;CODI_MUNICIPI;MUNICIPI;ESTACIO;CODI_CONTAMINANT;ANY;MES;DIA;H01;V01;H02;V02;H03;V03;H04;V04;H05;V05;H06;V06;H07;V07;H08;V08;H09;V09;H10;V10;H11;V11;H12;V12;H13;V13;H14;V14;H15;V15;H16;V16;H17;V17;H18;V18;H19;V19;H20;V20;H21;V21;H22;V22;H23;V23;H24;V24', axis='columns', inplace=True)

In [21]:
df = df.select_dtypes(exclude = object).copy()

In [20]:
df

,CODI_PROVINCIA,CODI_MUNICIPI,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,H02,H03,...,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24
0,8.0,19.0,4.0,7.0,2019.0,4.0,2.0,1.0,1.0,3.0,...,NaN,NaN,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0
1,8.0,19.0,4.0,7.0,2019.0,4.0,3.0,1.0,1.0,1.0,...,6.0,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0
2,8.0,19.0,4.0,7.0,2019.0,4.0,4.0,1.0,1.0,2.0,...,8.0,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0
3,8.0,19.0,4.0,7.0,2019.0,4.0,5.0,2.0,1.0,8.0,...,4.0,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0
4,8.0,19.0,4.0,7.0,2019.0,4.0,6.0,1.0,1.0,1.0,...,3.0,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,8.0,19.0,57.0,14.0,2019.0,10.0,27.0,12.0,4.0,NaN,...,82.0,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0
1205,8.0,19.0,57.0,14.0,2019.0,10.0,28.0,15.0,34.0,42.0,...,48.0,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0
1206,8.0,19.0,57.0,14.0,2019.0,10.0,29.0,41.0,50.0,63.0,...,26.0,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0
1207,8.0,19.0,57.0,14.0,2019.0,10.0,30.0,1.0,1.0,1.0,...,74.0,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0
1208,8.0,19.0,57.0,14.0,2019.0,10.0,31.0,43.0,62.0,66.0,...,42.0,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0

In [22]:
df.drop(columns=['CODI_PROVINCIA', 'CODI_MUNICIPI'], inplace=True)

In [23]:
df

,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,H02,H03,H04,H05,...,H15,H16,H17,H18,H19,H20,H21,H22,H23,H24
0,4.0,7.0,2019.0,4.0,2.0,1.0,1.0,3.0,1.0,1.0,...,NaN,NaN,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0
1,4.0,7.0,2019.0,4.0,3.0,1.0,1.0,1.0,1.0,1.0,...,6.0,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0
2,4.0,7.0,2019.0,4.0,4.0,1.0,1.0,2.0,4.0,1.0,...,8.0,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0
3,4.0,7.0,2019.0,4.0,5.0,2.0,1.0,8.0,2.0,2.0,...,4.0,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0
4,4.0,7.0,2019.0,4.0,6.0,1.0,1.0,1.0,1.0,1.0,...,3.0,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,57.0,14.0,2019.0,10.0,27.0,12.0,4.0,NaN,31.0,38.0,...,82.0,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0
1205,57.0,14.0,2019.0,10.0,28.0,15.0,34.0,42.0,74.0,77.0,...,48.0,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0
1206,57.0,14.0,2019.0,10.0,29.0,41.0,50.0,63.0,65.0,61.0,...,26.0,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0
1207,57.0,14.0,2019.0,10.0,30.0,1.0,1.0,1.0,1.0,1.0,...,74.0,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0
1208,57.0,14.0,2019.0,10.0,31.0,43.0,62.0,66.0,63.0,62.0,...,42.0,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0

#### Creating Date column converting years, months and days from floats to strings and putting together to get a date.

In [24]:
df['DATA'] = (df["ANY"].astype(str).apply(lambda x: x[:-2]) + "/"  + df["MES"].astype(str).apply(lambda x: x[:-2]) + "/" + df["DIA"].astype(str).apply(lambda x: x[:-2]))

In [25]:
df

,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,H02,H03,H04,H05,...,H16,H17,H18,H19,H20,H21,H22,H23,H24,DATA
0,4.0,7.0,2019.0,4.0,2.0,1.0,1.0,3.0,1.0,1.0,...,NaN,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0,2019/4/2
1,4.0,7.0,2019.0,4.0,3.0,1.0,1.0,1.0,1.0,1.0,...,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2019/4/3
2,4.0,7.0,2019.0,4.0,4.0,1.0,1.0,2.0,4.0,1.0,...,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0,2019/4/4
3,4.0,7.0,2019.0,4.0,5.0,2.0,1.0,8.0,2.0,2.0,...,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0,2019/4/5
4,4.0,7.0,2019.0,4.0,6.0,1.0,1.0,1.0,1.0,1.0,...,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0,2019/4/6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,57.0,14.0,2019.0,10.0,27.0,12.0,4.0,NaN,31.0,38.0,...,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0,2019/10/27
1205,57.0,14.0,2019.0,10.0,28.0,15.0,34.0,42.0,74.0,77.0,...,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0,2019/10/28
1206,57.0,14.0,2019.0,10.0,29.0,41.0,50.0,63.0,65.0,61.0,...,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0,2019/10/29
1207,57.0,14.0,2019.0,10.0,30.0,1.0,1.0,1.0,1.0,1.0,...,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0,2019/10/30
1208,57.0,14.0,2019.0,10.0,31.0,43.0,62.0,66.0,63.0,62.0,...,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0,2019/10/31

In [26]:
df['DATA'] = pd.to_datetime(df['DATA'], dayfirst=False, errors='coerce')

In [27]:
df

,ESTACIO,CODI_CONTAMINANT,ANY,MES,DIA,H01,H02,H03,H04,H05,...,H16,H17,H18,H19,H20,H21,H22,H23,H24,DATA
0,4.0,7.0,2019.0,4.0,2.0,1.0,1.0,3.0,1.0,1.0,...,NaN,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0,2019-04-02
1,4.0,7.0,2019.0,4.0,3.0,1.0,1.0,1.0,1.0,1.0,...,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2019-04-03
2,4.0,7.0,2019.0,4.0,4.0,1.0,1.0,2.0,4.0,1.0,...,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0,2019-04-04
3,4.0,7.0,2019.0,4.0,5.0,2.0,1.0,8.0,2.0,2.0,...,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0,2019-04-05
4,4.0,7.0,2019.0,4.0,6.0,1.0,1.0,1.0,1.0,1.0,...,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0,2019-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,57.0,14.0,2019.0,10.0,27.0,12.0,4.0,NaN,31.0,38.0,...,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0,2019-10-27
1205,57.0,14.0,2019.0,10.0,28.0,15.0,34.0,42.0,74.0,77.0,...,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0,2019-10-28
1206,57.0,14.0,2019.0,10.0,29.0,41.0,50.0,63.0,65.0,61.0,...,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0,2019-10-29
1207,57.0,14.0,2019.0,10.0,30.0,1.0,1.0,1.0,1.0,1.0,...,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0,2019-10-30
1208,57.0,14.0,2019.0,10.0,31.0,43.0,62.0,66.0,63.0,62.0,...,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0,2019-10-31

In [28]:
df.drop(columns=['ANY', 'MES', 'DIA'], inplace=True)

In [29]:
df

,ESTACIO,CODI_CONTAMINANT,H01,H02,H03,H04,H05,H06,H07,H08,...,H16,H17,H18,H19,H20,H21,H22,H23,H24,DATA
0,4.0,7.0,1.0,1.0,3.0,1.0,1.0,2.0,13.0,58.0,...,NaN,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0,2019-04-02
1,4.0,7.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,4.0,...,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2019-04-03
2,4.0,7.0,1.0,1.0,2.0,4.0,1.0,1.0,1.0,3.0,...,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0,2019-04-04
3,4.0,7.0,2.0,1.0,8.0,2.0,2.0,8.0,21.0,53.0,...,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0,2019-04-05
4,4.0,7.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,...,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0,2019-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,57.0,14.0,12.0,4.0,NaN,31.0,38.0,34.0,26.0,19.0,...,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0,2019-10-27
1205,57.0,14.0,15.0,34.0,42.0,74.0,77.0,69.0,45.0,53.0,...,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0,2019-10-28
1206,57.0,14.0,41.0,50.0,63.0,65.0,61.0,68.0,41.0,22.0,...,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0,2019-10-29
1207,57.0,14.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0,2019-10-30
1208,57.0,14.0,43.0,62.0,66.0,63.0,62.0,51.0,35.0,26.0,...,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0,2019-10-31

In [30]:
df['ESTACIO'] = df['ESTACIO'].astype(str).apply(lambda x: x[:-2])
df['CODI_CONTAMINANT'] = df['CODI_CONTAMINANT'].astype(str).apply(lambda x: x[:-2])

In [31]:
df

,ESTACIO,CODI_CONTAMINANT,H01,H02,H03,H04,H05,H06,H07,H08,...,H16,H17,H18,H19,H20,H21,H22,H23,H24,DATA
0,4,7,1.0,1.0,3.0,1.0,1.0,2.0,13.0,58.0,...,NaN,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0,2019-04-02
1,4,7,1.0,1.0,1.0,1.0,1.0,1.0,2.0,4.0,...,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2019-04-03
2,4,7,1.0,1.0,2.0,4.0,1.0,1.0,1.0,3.0,...,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0,2019-04-04
3,4,7,2.0,1.0,8.0,2.0,2.0,8.0,21.0,53.0,...,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0,2019-04-05
4,4,7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,...,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0,2019-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,57,14,12.0,4.0,NaN,31.0,38.0,34.0,26.0,19.0,...,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0,2019-10-27
1205,57,14,15.0,34.0,42.0,74.0,77.0,69.0,45.0,53.0,...,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0,2019-10-28
1206,57,14,41.0,50.0,63.0,65.0,61.0,68.0,41.0,22.0,...,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0,2019-10-29
1207,57,14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0,2019-10-30
1208,57,14,43.0,62.0,66.0,63.0,62.0,51.0,35.0,26.0,...,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0,2019-10-31

In [32]:
df.bfill(axis=0)

,ESTACIO,CODI_CONTAMINANT,H01,H02,H03,H04,H05,H06,H07,H08,...,H16,H17,H18,H19,H20,H21,H22,H23,H24,DATA
0,4,7,1.0,1.0,3.0,1.0,1.0,2.0,13.0,58.0,...,3.0,8.0,7.0,7.0,8.0,3.0,1.0,1.0,1.0,2019-04-02
1,4,7,1.0,1.0,1.0,1.0,1.0,1.0,2.0,4.0,...,3.0,6.0,3.0,3.0,3.0,2.0,2.0,2.0,2.0,2019-04-03
2,4,7,1.0,1.0,2.0,4.0,1.0,1.0,1.0,3.0,...,5.0,4.0,4.0,3.0,2.0,2.0,1.0,2.0,2.0,2019-04-04
3,4,7,2.0,1.0,8.0,2.0,2.0,8.0,21.0,53.0,...,5.0,5.0,5.0,3.0,3.0,2.0,2.0,1.0,2.0,2019-04-05
4,4,7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,...,3.0,5.0,4.0,4.0,6.0,2.0,2.0,1.0,3.0,2019-04-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1204,57,14,12.0,4.0,42.0,31.0,38.0,34.0,26.0,19.0,...,86.0,88.0,86.0,71.0,36.0,33.0,25.0,11.0,18.0,2019-10-27
1205,57,14,15.0,34.0,42.0,74.0,77.0,69.0,45.0,53.0,...,60.0,46.0,35.0,14.0,3.0,21.0,41.0,31.0,36.0,2019-10-28
1206,57,14,41.0,50.0,63.0,65.0,61.0,68.0,41.0,22.0,...,51.0,61.0,51.0,26.0,5.0,1.0,1.0,2.0,1.0,2019-10-29
1207,57,14,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,77.0,57.0,47.0,15.0,8.0,63.0,71.0,66.0,52.0,2019-10-30
1208,57,14,43.0,62.0,66.0,63.0,62.0,51.0,35.0,26.0,...,23.0,30.0,17.0,9.0,16.0,17.0,16.0,54.0,55.0,2019-10-31

In [38]:
df.to_csv('air_measurements_2019.csv', index=False)